"""Export evaluation artifacts under Skill_MAS/results/log/ (full + per-task + snapshots)."""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from .config import SCHEMA_ROUND_ARTIFACT_INDEX
from .secrets_redact import redact_vita_results_top_info


def _safe_task_dir_name(task_id: str) -> str:
    return task_id.replace("/", "_").replace("\\", "_")


_RESERVED_UNDER_ROUND = frozenset({"skills_snapshot", "per_task"})


def _task_dir_under_round(round_dir: Path, task_id: str) -> Path:
    safe = _safe_task_dir_name(task_id)
    if safe in _RESERVED_UNDER_ROUND or not safe:
        safe = f"task_{safe or 'unknown'}"
    return round_dir / safe


def export_evaluation_logs(
    *,
    results_path: Path,
    bench_id: str,
    run_id: str,
    round_idx: int,
    merged_skill_dir: Path | None,
    domain: str,
    task_ids: list[str],
    log_root: Path,
) -> Path:
    raw_text = results_path.read_text(encoding="utf-8")
    data = json.loads(raw_text)
    data = redact_vita_results_top_info(data)

    sims = data.get("simulations") or []

    round_dir = log_root / bench_id / run_id / f"round_{round_idx:02d}"
    round_dir.mkdir(parents=True, exist_ok=True)

    dest_full = round_dir / "simulation_full.json"
    dest_full.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")

    for sim in sims:
        tid = str(sim.get("task_id") or "unknown")
        tdir = _task_dir_under_round(round_dir, tid)
        tdir.mkdir(parents=True, exist_ok=True)

        (tdir / "simulation_run.json").write_text(
            json.dumps(sim, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        ri = sim.get("reward_info")
        if ri is not None:
            (tdir / "reward_info.json").write_text(
                json.dumps(ri, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

        msgs = sim.get("messages") or []
        sm_blocks: list[dict[str, Any]] = []
        for i, m in enumerate(msgs):
            if not isinstance(m, dict):
                continue
            if m.get("role") != "assistant":
                continue
            raw = m.get("raw_data")
            if not isinstance(raw, dict):
                continue
            sm = raw.get("skill_mas")
            if not sm:
                continue
            sm_blocks.append(
                {
                    "message_index": i,
                    "turn_idx": m.get("turn_idx"),
                    "skill_mas": sm,
                    "assistant_content_preview": (m.get("content") or "")[:2000],
                }
            )
        (tdir / "skill_mas_messages.json").write_text(
            json.dumps(sm_blocks, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        lines_out = []
        for b in sm_blocks:
            sm = b["skill_mas"]
            lines_out.append(
                f"[msg {b['message_index']}] selected_skill={sm.get('selected_skill')!r} "
                f"stages={sm.get('num_stages')}"
            )
        (tdir / "skill_mas_index.txt").write_text("\n".join(lines_out) + "\n", encoding="utf-8")

    manifest: dict[str, Any] = {
        "bench_id": bench_id,
        "run_id": run_id,
        "round_idx": round_idx,
        "domain": domain,
        "task_ids": task_ids,
        "task_log_layout": f"round_{round_idx:02d}/<task_id>/ — per-task exports are direct children of the round folder",
        "source_simulation_path": str(results_path.resolve()),
        "exported_simulation_full": str(dest_full.resolve()),
        "num_simulations": len(sims),
        "merged_skill_dir": str(merged_skill_dir.resolve()) if merged_skill_dir else None,
    }
    (round_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    if merged_skill_dir is not None and merged_skill_dir.is_dir():
        snap = round_dir / "skills_snapshot"
        if snap.exists():
            shutil.rmtree(snap)
        shutil.copytree(merged_skill_dir, snap)

    return round_dir


def export_optimizer_skills(
    *,
    log_root: Path,
    bench_id: str,
    run_id: str,
    after_round_idx: int,
    next_round_idx: int,
    general_skill_md: str,
    domain_skill_md: str,
) -> Path:
    d = log_root / bench_id / run_id / f"optimizer_round_{after_round_idx:02d}_to_{next_round_idx:02d}"
    d.mkdir(parents=True, exist_ok=True)
    (d / "general_SKILL.md").write_text(general_skill_md, encoding="utf-8")
    (d / "domain_SKILL.md").write_text(domain_skill_md, encoding="utf-8")
    (d / "README.txt").write_text(
        "Generated by Skill_MAS optimizer after analyzing summary for round "
        f"{after_round_idx}; these become round_{next_round_idx:02d} under artifacts/skills.\n",
        encoding="utf-8",
    )
    return d


def export_drb_evaluation_logs(
    *,
    bundle_path: Path,
    bench_id: str,
    run_id: str,
    round_idx: int,
    log_root: Path,
    merged_skill_dir: Path,
) -> Path:
    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    round_dir = log_root / bench_id / run_id / f"round_{round_idx:02d}"
    round_dir.mkdir(parents=True, exist_ok=True)

    (round_dir / "drb_bundle.json").write_text(
        json.dumps(bundle, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    raw_jsonl = Path(bundle["raw_jsonl"])
    if raw_jsonl.is_file():
        shutil.copy2(raw_jsonl, round_dir / raw_jsonl.name)

    qsub = Path(bundle["query_subset_jsonl"])
    if qsub.is_file():
        shutil.copy2(qsub, round_dir / qsub.name)

    race_txt = Path(bundle["race_result_txt"])
    if race_txt.is_file():
        (round_dir / "race_result.txt").write_text(
            race_txt.read_text(encoding="utf-8"),
            encoding="utf-8",
        )

    ptd = Path(bundle["process_trace_dir"])
    if ptd.is_dir():
        dest_pt = round_dir / "process_traces"
        if dest_pt.exists():
            shutil.rmtree(dest_pt)
        shutil.copytree(ptd, dest_pt)

    if merged_skill_dir.is_dir():
        snap = round_dir / "skills_snapshot"
        if snap.exists():
            shutil.rmtree(snap)
        shutil.copytree(merged_skill_dir, snap)

    manifest: dict[str, Any] = {
        "bench_id": bench_id,
        "run_id": run_id,
        "round_idx": round_idx,
        "bench_backend": "drb",
        "task_ids": bundle.get("task_ids"),
        "drb_bundle_path": str(bundle_path.resolve()),
        "merged_skill_dir": str(merged_skill_dir.resolve()),
        "race_result_txt": bundle.get("race_result_txt"),
    }
    (round_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return round_dir


def export_round_artifact_index(
    *,
    log_round_dir: Path,
    round_idx: int,
    trajectories_dir: Path,
    aspects_dir: Path,
    contrastive_dir: Path,
    skill_round_dir: Path,
    bank_meta_file: Path,
    knee_images_dir: Path,
) -> Path:
    payload: dict[str, Any] = {
        "schema": SCHEMA_ROUND_ARTIFACT_INDEX,
        "round_idx": round_idx,
        "trajectories_dir": str(trajectories_dir.resolve()) if trajectories_dir.exists() else str(trajectories_dir),
        "aspects_dir": str(aspects_dir.resolve()) if aspects_dir.exists() else str(aspects_dir),
        "contrastive_dir": str(contrastive_dir.resolve()) if contrastive_dir.exists() else str(contrastive_dir),
        "skill_round_dir": str(skill_round_dir.resolve()) if skill_round_dir.exists() else str(skill_round_dir),
        "bank_meta_file": str(bank_meta_file.resolve()) if bank_meta_file.exists() else str(bank_meta_file),
        "knee_images_dir": str(knee_images_dir.resolve()) if knee_images_dir.exists() else str(knee_images_dir),
    }
    p = log_round_dir / "round_artifact_index.json"
    p.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return p


def _copy_any(src: Path, dst: Path) -> bool:
    if not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
    else:
        shutil.copy2(src, dst)
    return True


def _copy_bundle_references(bundle_path: Path, out_dir: Path) -> list[str]:
    copied: list[str] = []
    try:
        bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    except Exception:
        return copied
    key_map = {
        "process_trace_dir": "process_traces",
        "raw_jsonl": "raw_jsonl.jsonl",
        "query_subset_jsonl": "query_subset.jsonl",
        "race_result_txt": "race_result.txt",
        "jsonl_file": "source_dataset.jsonl",
        "merged_skill_dir": "merged_skill_dir",
    }
    for key, alias in key_map.items():
        val = bundle.get(key)
        if not val:
            continue
        src = Path(str(val))
        dst = out_dir / alias
        if _copy_any(src, dst):
            copied.append(str(dst))
    return copied


def export_comprehensive_round_logs(
    *,
    log_round_dir: Path,
    round_root: Path,
    skill_round_dir: Path,
    bench_backend: str,
    by_task: dict[str, list[Any]],
) -> Path:
    """
    Export a comprehensive, backend-agnostic snapshot of one evolution round.

    This keeps all important intermediate artifacts under ``log_round_dir``:
    trajectories/aspects/contrastive, skill snapshot, and backend raw outputs
    (including bundles/process traces/sample logs/forward_code/workflow_state when available).
    """
    log_round_dir.mkdir(parents=True, exist_ok=True)
    details_dir = log_round_dir / "comprehensive"
    details_dir.mkdir(parents=True, exist_ok=True)

    copied: dict[str, list[str]] = {
        "round_artifacts": [],
        "skill_snapshot": [],
        "knee_images": [],
        "backend_raw": [],
        "bundle_expansions": [],
    }

    for name in ("trajectories", "aspects", "contrastive"):
        src = round_root / name
        dst = details_dir / name
        if _copy_any(src, dst):
            copied["round_artifacts"].append(str(dst))

    skill_dst = details_dir / "skills_snapshot"
    if _copy_any(skill_round_dir, skill_dst):
        copied["skill_snapshot"].append(str(skill_dst))
    knee_src = skill_round_dir / "knee_images"
    knee_dst = details_dir / "knee_images"
    if _copy_any(knee_src, knee_dst):
        copied["knee_images"].append(str(knee_dst))

    backend_raw = details_dir / "backend_raw"
    backend_raw.mkdir(parents=True, exist_ok=True)
    seen: set[str] = set()
    idx = 0
    for _, rows in by_task.items():
        for rec in rows:
            for raw in (getattr(rec, "log_path", ""), getattr(rec, "raw_result_path", "")):
                p = str(raw or "").strip()
                if not p or p in seen:
                    continue
                seen.add(p)
                src = Path(p)
                label = f"{idx:03d}_{src.name or 'artifact'}"
                dst = backend_raw / label
                if _copy_any(src, dst):
                    copied["backend_raw"].append(str(dst))
                    if src.is_file() and src.suffix.lower() == ".json" and "bundle_r" in src.name:
                        expanded = _copy_bundle_references(src, backend_raw / f"{label}_expanded")
                        copied["bundle_expansions"].extend(expanded)
                idx += 1

    manifest = {
        "schema": "skill_mas_round_comprehensive_log_v1",
        "bench_backend": bench_backend,
        "round_root": str(round_root),
        "skill_round_dir": str(skill_round_dir),
        "copied": copied,
    }
    mp = log_round_dir / "comprehensive_manifest.json"
    mp.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    return mp
